services:
  jupyterlab:
    container_name: jupyter-datascience
    user: root
    image: quay.io/jupyter/datascience-notebook:latest
    restart: always
    volumes:
      - ./notebooks:/home/jupyternb
      - ./custom_kernels:/home/jupyter/custom_kernels
      - ./kernels:/usr/local/share/jupyter/kernels
      - ./virtualenvs:/opt/virtualenvs
    environment:
      - JUPYTER_TOKEN=token
      - NB_USER=jupyternb
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
      - JUPYTER_PATH=/home/jupyter/custom_kernels
    working_dir: /home/jupyternb
    ports:
      - '8888:8888'
